[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

# API rewrite
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200